name: CI

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read # required by nrwl/nx-set-shas

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch the full history for Nx to determine affected projects
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'main'

      - uses: ./.github/actions/ci-setup
        with:
          job-name: 'lint'

      - name: Lint
        run: pnpm exec nx affected --target=lint:prettier,lint

  test-js:
    name: 'Test JavaScript: Node ${{ matrix.node-version }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ['16.20.x']

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'main'

      - uses: ./.github/actions/ci-setup
        with:
          job-name: 'test-js'
          node-version: ${{ matrix.node-version }}

      - name: Test
        run: pnpm exec nx affected --target=test:vitest

  test-py:
    name: 'Test Python: Python ${{ matrix.python-version }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8.x', '3.9.x', '3.10.x']

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'main'

      - uses: ./.github/actions/ci-setup
        with:
          job-name: 'test-py'
          python-version: ${{ matrix.python-version }}

      - name: Test
        run: pnpm exec nx affected --target=test:pytest

  docker-image:
    name: 'Build Docker image'
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          push: false
          # FIXME: change this to the actual Dockerfile name
          file: ./docker/example.Dockerfile
