# https://github.com/sveltejs/kit/blob/32afba695088b946aefe96da75b36de9b0667fbe/.github/workflows/release.yml
name: 'Code: Release'

on:
  push:
    branches: ['main']

permissions: {}

jobs:
  release:
    # prevents this action from running on forks
    # FIXME: [repo] change this to actual repo name
    if: github.repository == 'secretflow/web-template'
    uses: secretflow/web-ci/.github/workflows/release.yml@main
    secrets: inherit
